[env]
MISE_USE_VERSIONS_HOST = "0"

[tools]
actionlint = "latest"
hk = "latest"
jq = "latest"
lua = "5.4"
lua-language-server = "latest"
pkl = "latest"
stylua = "latest"

[tasks.format]
description = "Format Lua scripts"
run = "stylua metadata.lua hooks/ lib/"

[tasks.lint]
description = "Lint Lua scripts and GitHub Actions using hk"
run = "hk check"

[tasks.lint-fix]
description = "Fix linting issues"
run = "hk fix"

[tasks.use-plugin]
usage = '''
arg "<ncs_version>" help="NCS toolchain version" {
    default "3.2.1"
}
arg "<nrfutil_version>" help="nrfutil core module version" {
    default "latest"
}
'''
run = '''
NRFUTIL_VERSION="${usage_nrfutil_version:?}"
SDK_VERSION="${usage_ncs_version:?}"
mise use "ncs:nrfutil@${NRFUTIL_VERSION}"
mise use "ncs:toolchain@${SDK_VERSION}"
'''

[tasks.ci]
description = "Run all CI checks: lint → smoke-test → integration-test"
depends = ["lint", "format"]
usage = '''
arg "<ncs_version>" help="Zephyr SDK Version" {
    default "3.2.1"
}
'''
run = '''
WORKSPACE=$(mktemp -d)
NCS_TEST_VERSION="${usage_ncs_version:?}" mise run integration-test ${WORKSPACE}
'''
