name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  smoke-test:
    strategy:
      fail-fast: false
      matrix:
        version: ["3.2.1"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          experimental: true
          mise_toml: |
            [tools]
            uv = "latest"
            [env]
            BACKEND = "ncs"
            MISE_USE_VERSIONS_HOST = "0"
            BACKEND_VERSION = "${{ matrix.version }}"

            [tasks.test]
            description = "Tests"
            run = '''
            echo "Link!"
            mise plugins ln "${BACKEND:?}" .
            echo "Install!"
            mise  install "${BACKEND}:toolchain@${BACKEND_VERSION:?}"
            mise  install "${BACKEND}:west@${BACKEND_VERSION}"
            echo "ls-remote!"
            mise ls-remote "${BACKEND}:toolchain@${BACKEND_VERSION}"
            mise ls-remote "${BACKEND}:west@${BACKEND_VERSION}"
            echo "Exec!"
            mise x  -- arm-zephyr-eabi-gcc --version
            mise x  -- west --version
            echo "Finished!"
            '''
      - run: mise run test
